blank_issues_enabled: true

contact_links:
  - name: Documentation
    url: https://github.com/michaelyurachek/therecordcollect/blob/main/README.md
    about: Please review the documentation before opening an issue.

  - name: Support
    url: https://github.com/michaelyurachek/therecordcollect/discussions
    about: Ask questions and get community support.

  - name: Security Vulnerability
    url: mailto:michaelyurachek@gmail.com
    about: Please report security vulnerabilities privately.